New website
europace/api-schnellstart pull request #13
Opened 2020-09-17 14:29 UTC by MikeKrueger75

Link auf neue Website angepasst.

2020-09-17 14:31 UTC, schmidthappens requested changes
Warum hast du denn die Postman-Collection angepasst?

2020-09-17 14:31 UTC, schmidthappens commented on README.md
> +## 📣 Voraussetzung um diese Calls auszuführen:
Auf Emojis vorerst verzichten, da diese nicht korrekt interpretiert werden auf der API-Site

2020-09-17 15:13 UTC, MikeKrueger75 commented
> Warum hast du denn die Postman-Collection angepasst?

Wollte ich gar nicht... ich mach nochmal einen REVERT

2020-10-17 15:55 UTC, MikeKrueger75 commented
ich fange nochmal von vorn an

2020-10-17 15:55 UTC, closed without merging