Add report and kundenangaben
europace/api-schnellstart pull request #17
Opened 2021-02-01 08:38 UTC by MikeKrueger75

Report-API und Kundenangaben-API ergänzt

2021-02-01 10:36 UTC, roamingthings requested changes

2021-02-01 10:36 UTC, roamingthings commented on EUROPACE API Calls.postman_collection.json
> +								"key": "X-traceId",
```suggestion
								"key": "X-TraceId",
```
Wir verwenden `X-TraceId` mit einem grossen T.

2021-02-02 10:25 UTC, caspii submitted a review, later dismissed
Habe alle Calls einmal getestet. 

Auch die Reporting Calls. Mir fehlte erst das Scope, also war es eine gute Übung

💯

2021-02-02 10:25 UTC, caspii commented on EUROPACE API Calls.postman_collection.json
> +							"raw": "\t\t{\n            \"antragsteller\": \"BEANTRAGT\",\n\t\t\t\"produktAnbieter\": \"NICHT_BEARBEITET\",\n\t\t\t\"kommentar\": \"The API get the job done.\"\n\t\t}",
```suggestion
							"raw": "\t\t{\n            \"antragsteller\": \"BEANTRAGT\",\n\t\t\t\"produktAnbieter\": \"NICHT_BEARBEITET\",\n\t\t\t\"kommentar\": \"The API got the job done.\"\n\t\t}",
```

2021-02-02 10:25 UTC, caspii commented on EUROPACE API Calls.postman_collection.json
> +							"raw": "\t\t{\n            \"antragsteller\": \"BEANTRAGT\",\n\t\t\t\"produktAnbieter\": \"NICHT_BEARBEITET\",\n\t\t\t\"kommentar\": \"The API get the job done.\"\n\t\t}",
Rechtschreibung

2021-02-02 10:25 UTC, caspii commented on EUROPACE API Calls.postman_collection.json
> +							"raw": "{\n    \"partnerId\": \"{{PARTNER_ID}}}}\",\n    \"fromDay\": \"2019-01-01\"\n}"
Hier scheint mir bei `"{{PARTNER_ID}}}}\"` ein `}}` zu viel zu sein?

2021-02-02 15:12 UTC, MikeKrueger75 commented on EUROPACE API Calls.postman_collection.json
> +							"raw": "{\n    \"partnerId\": \"{{PARTNER_ID}}}}\",\n    \"fromDay\": \"2019-01-01\"\n}"
Korrigiert

2021-02-02 15:24 UTC, MikeKrueger75 commented
@KoneFuzius Wie bekomme ich jetzt meinen Pull-Request durch?

2021-02-03 08:37 UTC, merged